import torch

pairs = [
    ("the cat sat", "on the mat"),
    ("the dog ran", "in the park"),
    ("a man walks", "to the store"),
    ("she eats", "an apple"),
    ("birds fly", "in the sky"),
    ("the cat sleeps", "on the bed"),
    ("the dog barks", "at the mailman"),
    ("a woman reads", "a book"),
    ("he drinks", "some water"),
    ("fish swim", "in the sea"),
    ("the car is fast", "it goes quickly"),
    ("the sun shines", "it is a bright day"),
    ("the moon is full", "it is a dark night"),
    ("stars twinkle", "in the night sky"),
    ("rain falls", "from the clouds"),
    ("the computer works", "it is very useful"),
    ("the phone rings", "someone is calling"),
    ("music plays", "it is a nice song"),
    ("the door opens", "someone is here"),
    ("the window closes", "it is getting cold"),
    ("my cat sat", "on the chair"),
    ("the bird sings", "a beautiful song"),
    ("the child laughs", "he is happy"),
    ("the flower blooms", "it is spring"),
    ("the tree grows", "tall and strong"),
    ("the river flows", "to the ocean"),
    ("the fire burns", "hot and bright"),
    ("the wind blows", "through the trees"),
    ("the snow falls", "softly on the ground"),
    ("the ice melts", "in the sun"),
    ("my dog plays", "with a ball"),
    ("the sun sets", "in the west"),
    ("the moon rises", "in the east"),
    ("the stars shine", "brightly at night"),
    ("the rain stops", "the sun comes out"),
    ("the clouds disappear", "the sky is blue"),
    ("the leaves fall", "from the trees in autumn"),
    ("the wind whispers", "secrets in the night"),
    ("the waves crash", "on the shore"),
    ("the sand is warm", "on the beach"),
    ("my book is good", "i like it"),
    ("the coffee is hot", "i drink it"),
    ("the food is tasty", "i eat it"),
    ("the house is big", "i live there"),
    ("the city is busy", "i work there"),
    ("the world is big", "i explore it"),
    ("the sky is blue", "i see it"),
    ("the grass is green", "i walk on it"),
    ("the air is fresh", "i breathe it"),
    ("the water is clear", "i drink it"),
    ("my friend is nice", "i like him"),
    ("the teacher is smart", "i learn from her"),
    ("the student is hard working", "he studies a lot"),
    ("the doctor is helpful", "she cares for people"),
    ("the nurse is kind", "she helps the sick"),
    ("the farmer is strong", "he works the land"),
    ("the baker is skilled", "he makes good bread"),
    ("the artist is creative", "she paints beautiful pictures"),
    ("the writer is talented", "he writes great stories"),
    ("the musician is gifted", "she plays wonderful music"),
    ("the dancer is graceful", "she moves beautifully"),
    ("the actor is expressive", "he portrays emotions well"),
    ("the athlete is fit", "he trains hard"),
    ("the scientist is curious", "she explores the world"),
    ("the engineer is innovative", "he designs new things"),
    ("the programmer is skilled", "he writes good code"),
    ("the designer is creative", "she makes things look good"),
    ("the manager is organized", "he keeps things running smoothly"),
    ("the leader is inspiring", "she motivates people"),
    ("the speaker is articulate", "he expresses himself well"),
    ("the listener is attentive", "she pays attention"),
    ("the observer is perceptive", "he notices details"),
    ("the thinker is insightful", "she understands things deeply"),
    ("the learner is diligent", "he studies hard"),
    ("the worker is productive", "she gets things done"),
    ("the dreamer is imaginative", "he envisions new possibilities"),
    ("the creator is inventive", "she makes new things"),
    ("the innovator is resourceful", "he finds new solutions"),
    ("the explorer is adventurous", "she seeks new experiences"),
    ("the traveler is curious", "he visits new places"),
    ("the adventurer is daring", "she takes risks"),
    ("the pioneer is bold", "he leads the way"),
    ("the visionary is insightful", "she sees the future"),
    ("the leader is inspiring", "he motivates others"),
    ("the guide is helpful", "she shows the way"),
    ("the mentor is wise", "he shares his knowledge"),
    ("the coach is supportive", "she encourages growth"),
    ("the friend is loyal", "he is always there"),
    ("the partner is reliable", "she can be counted on"),
    ("the family is loving", "they care for each other"),
    ("the community is supportive", "they help each other"),
    ("the world is connected", "we are all together"),
    ("the future is bright", "we have hope"),
    ("the journey is long", "we will persevere"),
    ("the challenge is great", "we will overcome"),
    ("the opportunity is vast", "we will seize it"),
    ("the potential is limitless", "we will achieve it"),
    ("the dream is alive", "we will make it real"),
    ("the vision is clear", "we will make it happen"),
    ("the goal is worthy", "we will strive for it"),
    ("the purpose is meaningful", "we will live it"),
    ("the life is precious", "we will cherish it"),
    ("the moment is now", "we will seize it"),
    ("the time is right", "we will act"),
    ("the day is beautiful", "we will enjoy it"),
    ("the night is peaceful", "we will rest"),
    ("the morning is fresh", "we will begin anew"),
    ("the evening is calm", "we will reflect"),
    ("the season is changing", "we will adapt"),
    ("the year is new", "we will make it count"),
    ("the decade is starting", "we will shape it"),
    ("the century is unfolding", "we will witness it"),
    ("the era is dawning", "we will create it"),
    ("the cat is black", "it is a sleek animal"),
    ("the dog is brown", "it is a loyal friend"),
    ("the bird is blue", "it is a beautiful sight"),
    ("the fish is gold", "it is a valuable pet"),
    ("the horse is white", "it is a majestic creature"),
    ("the cow is big", "it gives milk"),
    ("the sheep is fluffy", "it gives wool"),
    ("the pig is pink", "it is a farm animal"),
    ("the chicken is yellow", "it lays eggs"),
    ("the duck is white", "it swims in the pond"),
    ("the goose is gray", "it honks loudly"),
    ("the turkey is brown", "it is a thanksgiving bird"),
    ("the owl is wise", "it hoots at night"),
    ("the eagle is strong", "it soars in the sky"),
    ("the hawk is fast", "it hunts for prey"),
    ("the robin is red", "it sings in the morning"),
    ("the sparrow is small", "it chirps in the trees"),
    ("the crow is black", "it caws loudly"),
    ("the pigeon is gray", "it coos softly"),
    ("the swan is graceful", "it glides on the water"),
    ("the peacock is colorful", "it displays its feathers"),
    ("the parrot is talkative", "it mimics human speech"),
    ("the hummingbird is tiny", "it hovers near flowers"),
    ("the butterfly is delicate", "it flits through the air"),
    ("the bee is busy", "it collects nectar"),
    ("the ant is industrious", "it carries food"),
    ("the spider is patient", "it waits for its prey"),
    ("the ladybug is lucky", "it brings good fortune"),
    ("the grasshopper is green", "it hops in the meadow"),
    ("the cricket is noisy", "it chirps at night"),
    ("the snail is slow", "it leaves a trail"),
    ("the worm is long", "it wriggles in the soil"),
    ("the fly is annoying", "it buzzes around"),
    ("the mosquito is pesky", "it bites and itches"),
    ("the beetle is shiny", "it crawls on the ground"),
    ("the caterpillar is fuzzy", "it eats leaves"),
    ("the dragonfly is iridescent", "it darts over the water"),
    ("the praying mantis is stealthy", "it ambushes its prey"),
    ("the scorpion is dangerous", "it has a venomous sting"),
    ("the tarantula is hairy", "it is a large spider"),
    ("the centipede is segmented", "it has many legs"),
    ("the millipede is slow", "it curls up when threatened"),
    ("the earthworm is helpful", "it aerates the soil"),
    ("the leech is parasitic", "it feeds on blood"),
    ("the slug is slimy", "it leaves a trail of mucus"),
    ("the tick is small", "it carries diseases"),
    ("the mite is tiny", "it is often unseen"),
    ("the flea is agile", "it jumps quickly"),
    ("the louse is parasitic", "it lives on hosts"),
    ("the gnat is annoying", "it swarms in the air"),
    ("the midge is small", "it is often overlooked"),
    ("the aphid is destructive", "it damages plants"),
    ("the weevil is harmful", "it infests crops"),
    ("the termite is destructive", "it eats wood"),
    ("the moth is nocturnal", "it flies at night"),
    ("the butterfly is diurnal", "it flies during the day"),
    ("the dragonfly is aerial", "it lives in the air"),
    ("the seahorse is aquatic", "it lives in the sea"),
    ("the chameleon is adaptable", "it changes color"),
    ("the gecko is nocturnal", "it hunts at night"),
    ("the iguana is large", "it basks in the sun"),
    ("the lizard is small", "it scurries on the ground"),
    ("the snake is slithery", "it moves without legs"),
    ("the turtle is slow", "it carries its home"),
    ("the tortoise is terrestrial", "it lives on land"),
    ("the frog is amphibious", "it lives in water and on land"),
    ("the toad is bumpy", "it has warts"),
    ("the salamander is slender", "it has a long tail"),
    ("the newt is aquatic", "it lives in ponds"),
    ("the caecilian is legless", "it looks like a worm"),
    ("the amphisbaena is burrowing", "it lives underground"),
    ("the worm snake is tiny", "it is often mistaken for a worm"),
    ("the blind snake is harmless", "it has no venom"),
    ("the thread snake is slender", "it is very small"),
    ("the sea snake is venomous", "it lives in the ocean"),
    ("the coral snake is colorful", "it has bright bands"),
    ("the milk snake is harmless", "it mimics the coral snake"),
    ("the garter snake is common", "it is found in many places"),
    ("the rat snake is large", "it eats rodents"),
    ("the python is constricting", "it squeezes its prey"),
    ("the boa is non-venomous", "it kills by constriction"),
    ("the viper is venomous", "it has fangs"),
    ("the cobra is hooded", "it has a distinctive hood"),
    ("the mamba is fast", "it is a deadly snake"),
    ("the krait is venomous", "it has a potent venom"),
    ("the taipan is aggressive", "it is a dangerous snake"),
    ("the death adder is deadly", "it has a short tail"),
    ("the rattlesnake is noisy", "it rattles its tail"),
    ("the copperhead is venomous", "it has a copper-colored head"),
    ("the cottonmouth is aggressive", "it has a white mouth"),
    ("the water moccasin is venomous", "it lives in water"),
    ("the sidewinder is fast", "it moves sideways"),
    ("the horned viper is venomous", "it has horns above its eyes"),
    ("the puff adder is slow", "it puffs up when threatened"),
    ("the gaboon viper is camouflaged", "it blends in with the leaves"),
    ("the bushmaster is large", "it is a tropical snake"),
    ("the fer-de-lance is venomous", "it is a pit viper"),
    ("the lancehead is dangerous", "it has a triangular head"),
    ("the eyelash viper is small", "it has scales above its eyes"),
    ("the tree viper is arboreal", "it lives in trees"),
    ("the pit viper is venomous", "it has heat-sensing pits"),
    ("the sea krait is aquatic", "it lives in the ocean"),
    ("the yellow bellied sea snake is venomous", "it has a yellow belly"),
    ("the beaked sea snake is venomous", "it has a hooked nose"),
    ("the olive sea snake is common", "it is found in many places"),
    ("the Dubois sea snake is venomous", "it has a potent venom"),
    ("the Stokes sea snake is venomous", "it has a spiny tail"),
    ("the spine bellied sea snake is venomous", "it has spines on its belly"),
    ("the small headed sea snake is venomous", "it has a small head"),
    ("the turtle headed sea snake is venomous", "it has a turtle-like head"),
    ("the flat tailed sea snake is aquatic", "it has a flat tail"),
    ("the banded sea krait is venomous", "it has black and white bands"),
    ("the blue sea snake is venomous", "it has a blue color"),
    ("the brown sea snake is venomous", "it has a brown color"),
    ("the black sea snake is venomous", "it has a black color"),
    ("the green sea snake is venomous", "it has a green color"),
    ("the yellow sea snake is venomous", "it has a yellow color"),
    ("the red sea snake is venomous", "it has a red color"),
    ("the orange sea snake is venomous", "it has an orange color"),
    ("the purple sea snake is venomous", "it has a purple color"),
    ("the pink sea snake is venomous", "it has a pink color"),
    ("the white sea snake is venomous", "it has a white color"),
    ("the gray sea snake is venomous", "it has a gray color"),
    ("the silver sea snake is venomous", "it has a silver color"),
    ("the gold sea snake is venomous", "it has a gold color"),
    ("the bronze sea snake is venomous", "it has a bronze color"),
    ("the copper sea snake is venomous", "it has a copper color"),
    ("the iron sea snake is venomous", "it has an iron color"),
    ("the steel sea snake is venomous", "it has a steel color"),
    ("the lead sea snake is venomous", "it has a lead color"),
    ("the tin sea snake is venomous", "it has a tin color"),
    ("the zinc sea snake is venomous", "it has a zinc color"),
    ("the mercury sea snake is venomous", "it has a mercury color"),
    ("the platinum sea snake is venomous", "it has a platinum color"),
    ("the uranium sea snake is venomous", "it has a uranium color"),
    ("the plutonium sea snake is venomous", "it has a plutonium color"),
    ("the kryptonite sea snake is venomous", "it has a kryptonite color"),
    ("the adamantium sea snake is venomous", "it has an adamantium color"),
    ("the vibranium sea snake is venomous", "it has a vibranium color"),
    ("the unobtanium sea snake is venomous", "it has an unobtanium color")
]

all_text = ' '.join([' '.join(pair) for pair in pairs]).split()
vocab = sorted(set(all_text + ['<pad>', '<sos>', '<eos>']))
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for w, i in word2idx.items()}

def encode(sentence):
    return [word2idx['<sos>']] + [word2idx[w] for w in sentence.split() if w in word2idx] + [word2idx['<eos>']]

def decode(indices):
    words = [idx2word[idx] for idx in indices if idx2word[idx] not in ['<sos>', '<eos>', '<pad>']]
    return ' '.join(words)

def get_batches():
    src_batch, tgt_batch = [], []
    for src, tgt in pairs:
        src_ids = encode(src)
        tgt_ids = encode(tgt)
        src_batch.append(src_ids)
        tgt_batch.append(tgt_ids)

    max_len = max(max(len(seq) for seq in src_batch), max(len(seq) for seq in tgt_batch))
    global MAX_LEN
    MAX_LEN = max_len

    src_batch = [seq + [word2idx['<pad>']]*(max_len-len(seq)) for seq in src_batch]
    tgt_batch = [seq + [word2idx['<pad>']]*(max_len-len(seq)) for seq in tgt_batch]
    src = torch.tensor(src_batch).to(torch.long)
    tgt = torch.tensor(tgt_batch).to(torch.long)
    return src, tgt

VOCAB_SIZE = len(vocab)  # Calculate VOCAB_SIZE *after* creating vocab
SOS_IDX = word2idx['<sos>']
EOS_IDX = word2idx['<eos>']
PAD_IDX = word2idx['<pad>']
# Calculate MAX_LEN here, after vocab and pairs are defined
MAX_LEN = max(len(encode(src)) for src, tgt in pairs)
# Calculate based on source sentences
print(f"Calculated MAX_LEN: {MAX_LEN}")

print("Vocabulary size:", VOCAB_SIZE)  # Debug: Check VOCAB_SIZE
